#!/usr/bin/env python
# -*- coding: utf8 -*-
# *****************************************************************
# **       PTS -- Python Toolkit for working with SKIRT          **
# **       © Astronomical Observatory, Ghent University          **
# *****************************************************************

## \package pts.storedtable.convert_kernel Functions for converting cumulative kernel tables to stored table format
#
# The function in this module can convert the cumulative kernel tables generated by the voxelise code
# (see Baes et al. 2026 in prep) from FITS format to stored table format.

# -----------------------------------------------------------------

import astropy.io.fits as fits
import numpy as np
from .io import writeStoredTable

# -----------------------------------------------------------------

## This function converts a cumulative kernel table generated by the voxelise code (see Baes et al. 2026 in prep)
# from FITS format to stored table format. It expects a single input file path pointing to the FITS file and
# a single output file path for the corresponding stab file.
#
# The stored table output file contains a three-dimensional table with X,Y,Z axes in range [0..1]. Both the axis
# values and tthe tabulated quantity values are dimensionless.
#
def convertCumulativeKernel(inFilePaths, outFilePaths):
    # get data cube
    data = fits.getdata(inFilePaths[0])

    # construct axis grid with appopriate number of points
    npoints = data.shape[0]
    grid = np.linspace(0., 1., npoints)

    # write stored table
    writeStoredTable(outFilePaths[0],
                    ['X','Y','Z'], ['1','1','1'], ['lin','lin','lin'], [grid,grid,grid],
                    ['Phi'], ['1'], ['lin'], [data])

# -----------------------------------------------------------------
