#!/usr/bin/env python
# -*- coding: utf8 -*-
# *****************************************************************
# **       PTS -- Python Toolkit for working with SKIRT          **
# **       © Astronomical Observatory, Ghent University          **
# *****************************************************************

# -----------------------------------------------------------------
#  Package initialization file
# -----------------------------------------------------------------

## \package pts.simulation.do Commands for working with HEALPix output from SKIRT
#
# The Python scripts residing in the do sub-directory of this package implement commands
# for working with files generated by the SKIRT HEALPixSkyInstrument.
#
