#!/usr/bin/env python
# -*- coding: utf8 -*-
# *****************************************************************
# **       PTS -- Python Toolkit for working with SKIRT          **
# **       © Astronomical Observatory, Ghent University          **
# *****************************************************************

## \package pts.visual.do.plot_grids Plot the spatial grids used in one or more SKIRT simulations
#
# This script creates wireframe plots for one or more text files generated by SKIRT's SpatialGridPlotProbe class.
# It takes the following arguments:
#  - \em outDirPath (positional string argument): the path to the SKIRT simulation output directory,
#                                                 or "." for the current directory
#  - \em prefix (string): the prefix of the simulation to handle; by default handles all simulations in the directory
#
# In all cases, the plot file is placed next to the "*_grid*.dat" file(s) being represented, with the filename
# extension replaced by ".pdf".
#

# -----------------------------------------------------------------

def do( outDirPath : (str,"SKIRT simulation output directory"),
        prefix : (str,"SKIRT simulation prefix") = "",
        ) -> "plot the spatial grids used in one or more SKIRT simulations":

    import pts.simulation as sm
    import pts.visual as vis

    for sim in sm.createSimulations(outDirPath, prefix if len(prefix)>0 else None):
        vis.plotGrids(sim)

# ----------------------------------------------------------------------
