#!/usr/bin/env python
# -*- coding: utf8 -*-
# *****************************************************************
# **       PTS -- Python Toolkit for working with SKIRT          **
# **       © Astronomical Observatory, Ghent University          **
# *****************************************************************

## \package pts.visual.do.plot_temperature_cuts Plot planar cuts through the dust temperature in one or more
# SKIRT simulations
#
# This script creates plots of the dust temperature cuts generated by the DefaultDustTemperatureCutsProbe in a SKIRT
# simulation.
#
# The script requires that the simulation includes exactly one DefaultDustTemperatureCutsProbe.
# If this is not the case, the script does nothing.
#
# The script takes the following arguments:
#  - \em outDirPath (positional string argument): the path to the SKIRT simulation output directory,
#                                                 or "." for the current directory
#  - \em prefix (string): the prefix of the simulation to handle; by default handles all simulations in the directory
#
# In all cases, the plot file is placed next to the simulation output file(s) being handled. The filename includes
# the simulation prefix, the probe name, and the medium indicator, and has the ".pdf" filename extension.
#

# -----------------------------------------------------------------

def do( outDirPath : (str,"SKIRT simulation output directory"),
        prefix : (str,"SKIRT simulation prefix") = "",
        ) -> "plot the planar cuts through the temperature in one or more SKIRT simulations":

    import pts.simulation as sm
    import pts.visual as vis

    for sim in sm.createSimulations(outDirPath, prefix if len(prefix)>0 else None):
        probes = [probe for probe in sim.probes() if probe.type() == "DefaultDustTemperatureCutsProbe"]
        if len(probes) == 1:
            probe = probes[0]

            plotFileName = "{}_dust_T.pdf".format(probe.name())
            vis.plotDefaultDustTemperatureCuts(sim, plotFilePath=sim.outFilePath(plotFileName))

# ----------------------------------------------------------------------
