#!/usr/bin/env python
# -*- coding: utf8 -*-
# *****************************************************************
# **       PTS -- Python Toolkit for working with SKIRT          **
# **       © Astronomical Observatory, Ghent University          **
# *****************************************************************

## \package pts.visual.do.plot_magnetic_field_cuts Plot planar cuts through the magnetic field in a SKIRT input model
#
# This script creates vector plots of magnetic field cuts generated by the DefaultMagneticFieldCutsProbe or
# PlanarMagneticFieldCutsProbe in a SKIRT simulation, allowing a visual evaluation of the magnetic field in the
# SKIRT input model.
#
# If the simulation does not include any DefaultMagneticFieldCutsProbe or PlanarMagneticFieldCutsProbe instances,
# the script does nothing.
#
# The script takes the following arguments:
#  - \em simDirPath (positional string argument): the path to the SKIRT simulation output directory,
#                                                 or "." for the current directory
#  - \em prefix (string): the prefix of the simulation to handle; by default handles all simulations in the directory
#  - \em bin: the number of pixels in each bin in both horizontal and vertical directions.
#
# In all cases, the plot file is placed next to the simulation output file(s) being handled. The filename includes
# the simulation prefix, the probe name and a cut indicator, and has the ".pdf" filename extension.
#

# -----------------------------------------------------------------

def do( simDirPath : (str, "SKIRT simulation output directory"),
        prefix : (str,"SKIRT simulation prefix") = "",
        bin : (int,"number of pixels in a bin, in both x and y directions") = 32,
        ) -> "plot the planar cuts through the magnetic field in one or more SKIRT simulations":

    import pts.simulation as sm
    import pts.visual as vis

    for sim in sm.createSimulations(simDirPath, prefix if len(prefix) > 0 else None):
        vis.plotMagneticFieldCuts(sim, binSize=(bin,bin))

# ----------------------------------------------------------------------
